version: '3'
services:
  api:
    build: ./api
    ports:
    - 9001:80
    volumes:
    - ./api/:/usr/src/app/
    - ./config/:/usr/src/app/config/
    container_name: api
  website:
    build: ./website
    ports:
    - 9000:80
    volumes:
    - ./website/:/usr/src/app/
    - ./config/:/usr/src/app/config/
    container_name: website
    depends_on:
    - api
  pinboard:
    build: ./pinboard
    ports:
    - 9002:3000
    - 9003:3001
    volumes:
    - ./pinboard/:/usr/src/app/
    - ./config/:/usr/src/app/config/
    container_name: pinboard